<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

class PermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Role::create(['name' => 'Administrator']);
        Role::create(['name' => 'Editor CMS']);
        Role::create(['name' => 'Kasir Reservasi']);
        Role::create(['name' => 'Kasir Inventory']);
        Role::create(['name' => 'OP Parkir']);
        
        Permission::create(['name' => 'dashboard-list']);
        Permission::create(['name' => 'dashboard-graph']);
        Permission::create(['name' => 'dashboard-widget']);
        Permission::create(['name' => 'dashboard-table']);
        Permission::create(['name' => 'wahana-list']);
        Permission::create(['name' => 'wahana-create']);
        Permission::create(['name' => 'wahana-edit']);
        Permission::create(['name' => 'wahana-delete']);
        Permission::create(['name' => 'kupon-list']);
        Permission::create(['name' => 'kupon-create']);
        Permission::create(['name' => 'kupon-edit']);
        Permission::create(['name' => 'kupon-delete']);
        Permission::create(['name' => 'monitoring-list']);
        Permission::create(['name' => 'inventory-kategori-list']);
        Permission::create(['name' => 'inventory-kategori-create']);
        Permission::create(['name' => 'inventory-kategori-edit']);
        Permission::create(['name' => 'inventory-kategori-delete']);
        Permission::create(['name' => 'inventory-produk-list']);
        Permission::create(['name' => 'inventory-produk-create']);
        Permission::create(['name' => 'inventory-produk-edit']);
        Permission::create(['name' => 'inventory-produk-delete']);
        Permission::create(['name' => 'inventory-purchasing-list']);
        Permission::create(['name' => 'inventory-purchasing-create']);
        Permission::create(['name' => 'inventory-purchasing-edit']);
        Permission::create(['name' => 'inventory-purchasing-delete']);
        Permission::create(['name' => 'inventory-stock-list']);
        Permission::create(['name' => 'inventory-stock-edit']);
        Permission::create(['name' => 'inventory-stock-delete']);
        Permission::create(['name' => 'cms-company-list']);
        Permission::create(['name' => 'cms-company-edit']);
        Permission::create(['name' => 'cms-kontak-list']);
        Permission::create(['name' => 'cms-kontak-edit']);
        Permission::create(['name' => 'cms-terms-list']);
        Permission::create(['name' => 'cms-terms-edit']);
        Permission::create(['name' => 'cms-faq-list']);
        Permission::create(['name' => 'cms-faq-create']);
        Permission::create(['name' => 'cms-faq-edit']);
        Permission::create(['name' => 'cms-faq-delete']);
        Permission::create(['name' => 'cms-policy-list']);
        Permission::create(['name' => 'cms-policy-edit']);
        Permission::create(['name' => 'cms-blog-kategori-list']);
        Permission::create(['name' => 'cms-blog-kategori-create']);
        Permission::create(['name' => 'cms-blog-kategori-edit']);
        Permission::create(['name' => 'cms-blog-kategori-delete']);
        Permission::create(['name' => 'cms-blog-artikel-list']);
        Permission::create(['name' => 'cms-blog-artikel-create']);
        Permission::create(['name' => 'cms-blog-artikel-edit']);
        Permission::create(['name' => 'cms-blog-artikel-delete']);
        Permission::create(['name' => 'kasir-inventory-list']);
        Permission::create(['name' => 'kasir-inventory-create']);
        Permission::create(['name' => 'kasir-reservasi-list']);
        Permission::create(['name' => 'kasir-reservasi-create']);
        Permission::create(['name' => 'kasir-checkin-list']);
        Permission::create(['name' => 'kasir-checkin-create']);
        Permission::create(['name' => 'kasir-checkout-list']);
        Permission::create(['name' => 'kasir-checkout-create']);
        Permission::create(['name' => 'parkir-data-list']);
        Permission::create(['name' => 'parkir-data-edit']);
        Permission::create(['name' => 'parkir-data-delete']);
        Permission::create(['name' => 'parkir-in-list']);
        Permission::create(['name' => 'parkir-in-create']);
        Permission::create(['name' => 'parkir-out-list']);
        Permission::create(['name' => 'parkir-out-create']);
        Permission::create(['name' => 'role-list']);
        Permission::create(['name' => 'role-create']);
        Permission::create(['name' => 'role-edit']);
        Permission::create(['name' => 'role-delete']);
        Permission::create(['name' => 'user-list']);
        Permission::create(['name' => 'user-create']);
        Permission::create(['name' => 'user-edit']);
        Permission::create(['name' => 'user-delete']);
        Permission::create(['name' => 'report-reservasi']);
        Permission::create(['name' => 'report-inventory']);
        Permission::create(['name' => 'report-parkir']);
        Permission::create(['name' => 'report-purchasing']);

        $roleAdministrator = Role::findByName('Administrator');
        $roleAdministrator->givePermissionTo('dashboard-list');
        $roleAdministrator->givePermissionTo('dashboard-graph');
        $roleAdministrator->givePermissionTo('dashboard-widget');
        $roleAdministrator->givePermissionTo('dashboard-table');
        $roleAdministrator->givePermissionTo('wahana-list');
        $roleAdministrator->givePermissionTo('wahana-create');
        $roleAdministrator->givePermissionTo('wahana-edit');
        $roleAdministrator->givePermissionTo('wahana-delete');
        $roleAdministrator->givePermissionTo('kupon-list');
        $roleAdministrator->givePermissionTo('kupon-create');
        $roleAdministrator->givePermissionTo('kupon-edit');
        $roleAdministrator->givePermissionTo('kupon-delete');
        $roleAdministrator->givePermissionTo('monitoring-list');
        $roleAdministrator->givePermissionTo('inventory-kategori-list');
        $roleAdministrator->givePermissionTo('inventory-kategori-create');
        $roleAdministrator->givePermissionTo('inventory-kategori-edit');
        $roleAdministrator->givePermissionTo('inventory-kategori-delete');
        $roleAdministrator->givePermissionTo('inventory-produk-list');
        $roleAdministrator->givePermissionTo('inventory-produk-create');
        $roleAdministrator->givePermissionTo('inventory-produk-edit');
        $roleAdministrator->givePermissionTo('inventory-produk-delete');
        $roleAdministrator->givePermissionTo('inventory-purchasing-list');
        $roleAdministrator->givePermissionTo('inventory-purchasing-create');
        $roleAdministrator->givePermissionTo('inventory-purchasing-edit');
        $roleAdministrator->givePermissionTo('inventory-purchasing-delete');
        $roleAdministrator->givePermissionTo('inventory-stock-list');
        $roleAdministrator->givePermissionTo('inventory-stock-edit');
        $roleAdministrator->givePermissionTo('cms-company-list');
        $roleAdministrator->givePermissionTo('cms-company-edit');
        $roleAdministrator->givePermissionTo('cms-kontak-list');
        $roleAdministrator->givePermissionTo('cms-kontak-edit');
        $roleAdministrator->givePermissionTo('cms-terms-list');
        $roleAdministrator->givePermissionTo('cms-terms-edit');
        $roleAdministrator->givePermissionTo('cms-faq-list');
        $roleAdministrator->givePermissionTo('cms-faq-edit');
        $roleAdministrator->givePermissionTo('cms-policy-list');
        $roleAdministrator->givePermissionTo('cms-policy-edit');
        $roleAdministrator->givePermissionTo('cms-blog-kategori-list');
        $roleAdministrator->givePermissionTo('cms-blog-kategori-create');
        $roleAdministrator->givePermissionTo('cms-blog-kategori-edit');
        $roleAdministrator->givePermissionTo('cms-blog-kategori-delete');
        $roleAdministrator->givePermissionTo('cms-blog-artikel-list');
        $roleAdministrator->givePermissionTo('cms-blog-artikel-create');
        $roleAdministrator->givePermissionTo('cms-blog-artikel-edit');
        $roleAdministrator->givePermissionTo('cms-blog-artikel-delete');
        $roleAdministrator->givePermissionTo('kasir-inventory-list');
        $roleAdministrator->givePermissionTo('kasir-inventory-create');
        $roleAdministrator->givePermissionTo('kasir-reservasi-list');
        $roleAdministrator->givePermissionTo('kasir-reservasi-create');
        $roleAdministrator->givePermissionTo('kasir-checkin-list');
        $roleAdministrator->givePermissionTo('kasir-checkin-create');
        $roleAdministrator->givePermissionTo('kasir-checkout-list');
        $roleAdministrator->givePermissionTo('kasir-checkout-create');
        $roleAdministrator->givePermissionTo('parkir-data-list');
        $roleAdministrator->givePermissionTo('parkir-data-edit');
        $roleAdministrator->givePermissionTo('parkir-data-delete');
        $roleAdministrator->givePermissionTo('parkir-in-list');
        $roleAdministrator->givePermissionTo('parkir-in-create');
        $roleAdministrator->givePermissionTo('parkir-out-list');
        $roleAdministrator->givePermissionTo('parkir-out-create');
        $roleAdministrator->givePermissionTo('role-list');
        $roleAdministrator->givePermissionTo('role-create');
        $roleAdministrator->givePermissionTo('role-edit');
        $roleAdministrator->givePermissionTo('role-delete');
        $roleAdministrator->givePermissionTo('report-reservasi');
        $roleAdministrator->givePermissionTo('report-inventory');
        $roleAdministrator->givePermissionTo('report-parkir');
        $roleAdministrator->givePermissionTo('report-purchasing');

        $roleEditor = Role::findByName('Editor CMS');
        $roleEditor->givePermissionTo('dashboard-list');
        $roleEditor->givePermissionTo('cms-company-list');
        $roleEditor->givePermissionTo('cms-company-edit');
        $roleEditor->givePermissionTo('cms-kontak-list');
        $roleEditor->givePermissionTo('cms-kontak-edit');
        $roleEditor->givePermissionTo('cms-terms-list');
        $roleEditor->givePermissionTo('cms-terms-edit');
        $roleEditor->givePermissionTo('cms-faq-list');
        $roleEditor->givePermissionTo('cms-faq-edit');
        $roleEditor->givePermissionTo('cms-policy-list');
        $roleEditor->givePermissionTo('cms-policy-edit');
        $roleEditor->givePermissionTo('cms-blog-kategori-list');
        $roleEditor->givePermissionTo('cms-blog-kategori-create');
        $roleEditor->givePermissionTo('cms-blog-kategori-edit');
        $roleEditor->givePermissionTo('cms-blog-kategori-delete');
        $roleEditor->givePermissionTo('cms-blog-artikel-list');
        $roleEditor->givePermissionTo('cms-blog-artikel-create');
        $roleEditor->givePermissionTo('cms-blog-artikel-edit');
        $roleEditor->givePermissionTo('cms-blog-artikel-delete');

        $roleKasirReservasi = Role::findByName('Kasir Reservasi');
        $roleKasirReservasi->givePermissionTo('dashboard-list');
        $roleKasirReservasi->givePermissionTo('kasir-reservasi-list');
        $roleKasirReservasi->givePermissionTo('kasir-reservasi-create');
        $roleKasirReservasi->givePermissionTo('kasir-checkin-list');
        $roleKasirReservasi->givePermissionTo('kasir-checkin-create');
        $roleKasirReservasi->givePermissionTo('kasir-checkout-list');
        $roleKasirReservasi->givePermissionTo('kasir-checkout-create');

        $roleKasirInventory = Role::findByName('Kasir Inventory');
        $roleKasirInventory->givePermissionTo('dashboard-list');
        $roleKasirInventory->givePermissionTo('kasir-inventory-list');
        $roleKasirInventory->givePermissionTo('kasir-inventory-create');

        $roleParkir = Role::findByName('OP Parkir');
        $roleParkir->givePermissionTo('dashboard-list');
        $roleParkir->givePermissionTo('parkir-data-list');
        $roleParkir->givePermissionTo('parkir-data-edit');
        $roleParkir->givePermissionTo('parkir-data-delete');
        $roleParkir->givePermissionTo('parkir-in-list');
        $roleParkir->givePermissionTo('parkir-in-create');
        $roleParkir->givePermissionTo('parkir-out-list');
        $roleParkir->givePermissionTo('parkir-out-create');
    }
}
